FROM python:3.6.9-slim
# FROM ubuntu:18.04

# Set environment variables
# ARG DEBIAN_FRONTEND=noninteractive
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONFAULTHANDLER 1
ENV PYTHONUNBUFFERED 1
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8


# RUN apt update && apt install -y \
#     gcc python3 python3-pip python3-dev 

# Set work directory
RUN mkdir /code
WORKDIR /code

# Install dependencies into a virtualenv
RUN pip3 install --upgrade pipenv
COPY ./Pipfile .
# COPY ./Pipfile.lock .
RUN pipenv lock
RUN pipenv install --dev --deploy

# Copy project code
# COPY . /code/